services:
  merezzco_agent:
    build: ./agent
    container_name: merezzco_agent
    ports:
      - "8000:8000"
    volumes:
      - ./agent:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - API_KEY=${API_KEY}


  n8n:
    image: n8nio/n8n:latest
    container_name: merezzco_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL= https://dolores-nondevelopable-streakedly.ngrok-free.dev/

    volumes:
      - ./n8n_data:/home/node/.n8n  # Persistencia de tus flujos
    depends_on:
      - merezzco_agent

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    command: tunnel --url http://n8n:5678



#  evolution-api:
#    container_name: evolution_api
#    image: atendai/evolution-api:v2.1.1
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    volumes:
#      - evolution_instances:/evolution/instances
#
#volumes:
#  evolution_instances: